### ISSUE TITLE
T-shirt Autonomobile 

### ISSUE THREAD

**Issue by MaxMartelo** [Autonomobile/AutoPylot#24]
Price per T-shirt : 20€ (logo Autonomobile + Texte)
If you are okay, I need a better quality logo

**Comment by MaxMartelo** [comment]
![1 Atomatic](https://user-images.githubusercontent.com/91148064/150674425-b6852a72-f64b-4be5-bd38-aac08d6c904e.PNG)

**Comment by MaxMartelo** [comment]
![2 Berksbire](https://user-images.githubusercontent.com/91148064/150674431-3a8d9e4e-906b-4c65-ba58-fff22f13ab40.PNG)

**Comment by MaxMartelo** [comment]
![3 Silver Face](https://user-images.githubusercontent.com/91148064/150674437-3b4b7b9d-6d17-4231-b199-382526051026.PNG)

**Comment by MaxMartelo** [comment]
![4 Stencil](https://user-images.githubusercontent.com/91148064/150674441-e20065f0-abd5-4f4c-bdeb-7bb0b0e63879.PNG)

**Comment by MaxMartelo** [comment]
Please choose which one do you prefer !!!

**Comment by MaxMartelo** [comment]
![1](https://user-images.githubusercontent.com/91148064/150674531-af24a14a-1f36-48e7-8f78-5189217f7fef.PNG)

**Comment by Maximellerbach** [comment]
Hahaha the logo is straight dégueulasse.

**Comment by Maximellerbach** [comment]
What is the Font used in the logo, maybe we can re-use it for the "Autonomobile team" ?

**Comment by MaxMartelo** [comment]
I don't know, we need to ask Dieu Crevette

**Comment by DieuCrevette** [comment]
je vous tiens au courant pour le logo mdr

**Comment by DieuCrevette** [comment]
Logo HD mis a jour (mais tj en fond blanc j'aurais une version en fond transparent bientôt)

aussi il y a un artefact un peu bizarre en haut, j'arrive pas a m'en débarrasser, il apparait lors de l’export mais rognant un chouilla l'image ca devrait etre bon.

**Comment by DieuCrevette** [comment]
Pour les t-shirt ils faut viser du 150g/m^2 (min) pour le poids, pour pas se retrouvé à payer 15 balles pour un torchon.

j'ai répertorier quelque sites : 

1. https://www.spreadshirt.fr/
2. https://creer-son-tshirt.fr/
3. https://www.printful.com (mais pas sur que l'on peuvent)
4. https://lateliertextile.f (certaines pages du sites ne sont pas encrypté )

Hésitez pas à me dire ce que vous en penser et si vous en trouvé d'autre.

**Comment by DieuCrevette** [comment]
Sur toutes les images le logo ce situe au maximum en haut a droite.
Site 1
![image](https://user-images.githubusercontent.com/92374888/152049467-685460f7-4a5a-4dd1-825f-177b6624a946.png)

Site 2 
![image](https://user-images.githubusercontent.com/92374888/152049335-43c8cc08-4fbe-45e4-8fc7-55a6b2bb7ab2.png)

Site 3 (t-shirt 220g soit bonne qualité)
![image](https://user-images.githubusercontent.com/92374888/152050260-23a68026-a61f-411e-aa4c-5e658bb7b211.png)

Site 4
![image](https://user-images.githubusercontent.com/92374888/152050481-2a2dab91-9ef8-42e5-b278-44f36e72fa27.png)

**Comment by MaxMartelo** [comment]
le site le plus intéressant c'est le 1 : https://www.spreadshirt.fr/    Je l'avais déjà vu.
Et sinon en noir le t shit est pas mal mais il faudrait AutoPylot en blanc et pas noir sur noir.
Donc je pense rester sur du blanc classique c'est bien, si vous êtes chaud, je peux en commander 1 taille S avec AutoPylot derrière et le logo devant ? on peu voir ça ensemble demain si vous êtes chaud ? @Maximellerbach @mickael-btc @DieuCrevette

**Comment by DieuCrevette** [comment]
le premier ou le 3eme sachant que niveau qualité je pense le 3 est mieux

**Comment by MaxMartelo** [comment]
En effet ce site est pas mal, mais est ce qu'on peu mettre des écritures à l'arrière ? 
En plus les prix sont pas trop cher

**Comment by DieuCrevette** [comment]
Yes on peut sans probleme @MaxMartelo
