### ISSUE TITLE
Dataset class

### ISSUE THREAD

**Issue by Maximellerbach** [Autonomobile/AutoPylot#30]
Create a dataset class to load and save folders of data, we will consider one folder to be a dataset.
We will have to develop:
- [x] a load dataset function
- [x] a load multiple dataset function (taking in input multiples paths)
- [x] every load functions but with sorted data
- [x] every load functions but with sequences of sorted data

quick reminder: the images will have in its name the date (fetch the date using the time.time() function) followed by .png, the json should have the same name but should end with .json instead of .png

You will need to use the glob.glob() function to fetch the path of every json path in the folder

**Comment by MaxMartelo** [comment]
Simple questions : 
What are the tasks "every load function but with sorted data / with sequences of sorted data ? 
And just to be sure, when we talk about a dataset, it is a folder wich have json file  and in this json file we have some pictures.png ?  @Maximellerbach

**Comment by Maximellerbach** [comment]
Its basically a load function but with the given constraints
