### ISSUE TITLE
Datagenerator

### ISSUE THREAD

**Issue by Maximellerbach** [Autonomobile/AutoPylot#48]
datagenerator class to load data during the training of the model

**Comment by AlexandreGirold** [comment]
Questions : 

- [ ] For X / Y coordinates do we want for each pixel of the image or for the image itself ? 

- [ ] Where will the pictures be saved ?

**Comment by Maximellerbach** [comment]
@AirlexandreGirold X and Y are "sets" of data.
X needs to contain everything that the model will have as inputs, and Y must contain everything that the model should expect as result.
I feel like you didn't get this part.

**Comment by AlexandreGirold** [comment]
Nop indeed didn't get it...

**Comment by Maximellerbach** [comment]
For the images, you don't have to worry about where they will be saved, they will be saved in an external folder.

**Comment by Maximellerbach** [comment]
Note: once datagenerator is finished and merged, rebase #63 and merge #63
