### ISSUE TITLE
Issue with image types coming from sim / webcam

### ISSUE THREAD

**Issue by Maximellerbach** [Autonomobile/AutoPylot#77]
Need to investigate the difference between data coming from simulator and webcam (one is np.uint8 and the other np.float64), will need to make both have the same type to avoid any future issues

**Comment by mickael-btc** [comment]
look for this function in transformers.py
```python
def noise(image_data):
        image_data["image"] += np.random.uniform(-25, 25, size=settings.IMAGE_SHAPE)
```
with training it create some errors

**Comment by Maximellerbach** [comment]
@mickael-btc fixed in https://github.com/Autonomobile/AutoPylot/pull/78/files#diff-179ef3b6f3f35eb9ac8fdfce02421a9819b5e7daf0f0123ea8dc6534648771f9R87
