### ISSUE TITLE
Add Settings to autopylot

### ISSUE THREAD

**Issue by mickael-btc** [Autonomobile/AutoPylot#79]
I think autopylot is lacking of some basic but important settings:
for instance i would like to have a `CONST_SPEED: true|false` which will describe if the model has to take speed from prediction or from a constant value.
This constant value may be store in another parameter of type float `MAX_SPEED` which will contain the maxim speed the car can approach. in the case CONST_SPEED is false, MAX_SPEED is the actual speed of the car

**Comment by Maximellerbach** [comment]
see #86
