### ISSUE TITLE
Load and Save data

### ISSUE THREAD

**Issue by Maximellerbach** [Autonomobile/AutoPylot#9]
Load and save images using opencv (cv2)

- one function to load images using a filename
- one function to save the image using a filename
- one function to load .json files
- one function to save .json files
- functions that combine both
- create tests for those functions

**Comment by DieuCrevette** [comment]
what do you mean by combining both ?

**Comment by Maximellerbach** [comment]
@DieuCrevette load an image associated to a json file. A function that takes as input the path of the json file, deduce the path of the image (remove the .json and add the .png) and then load the image. Then return the image and json.
pseudo code example:
```
def load_both (json_path):
    json_data = load_json(json_path)
    image_path = get_image_path(json_data)
    image = load_image(image_path)
    return image, json_data
```
